apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-ingressv2
  namespace: argocd

spec:
  rules:
    - host: argocd.dommehut.xyz
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: argocd-server
                port:
                  number: 80
